### ISSUE TITLE
DIY minimit

### ISSUE THREAD

**Issue by gamerabbit16** [multiplie-fr/minimit-beta#53]
Salut,
Je voudrais faire un minimit chez moi et je voudrais savoir comment je peut le faire? 
De quelle pièce j'ai besoin, quelle esp il faut utilisé ?

**Comment by multiplie-fr** [comment]
Bonjour,

Je viens d'ajouter la BOM au repository (https://github.com/multiplie-fr/minimit/tree/main/electronique).
Normalement il y a tout pour refaire une carte !

O.
